version: '3.2'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=users