server:
  port: ${PORT:9001}
spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    url: ${POSTGRES_URI:jdbc:postgresql://localhost:5433/offense_bd}


